//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gizmo.Shared.Resources.Autogenerated {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gizmo.Shared.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advance.
        /// </summary>
        public static string ADVANCE_PAYMENTS_RUSSIA_ADVANCE {
            get {
                return ResourceManager.GetString("ADVANCE_PAYMENTS_RUSSIA_ADVANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full payment.
        /// </summary>
        public static string ADVANCE_PAYMENTS_RUSSIA_FULL_PAYMENT {
            get {
                return ResourceManager.GetString("ADVANCE_PAYMENTS_RUSSIA_FULL_PAYMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full prepayment.
        /// </summary>
        public static string ADVANCE_PAYMENTS_RUSSIA_FULL_PREPAYMENT {
            get {
                return ResourceManager.GetString("ADVANCE_PAYMENTS_RUSSIA_FULL_PREPAYMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepayment.
        /// </summary>
        public static string ADVANCE_PAYMENTS_RUSSIA_PREPAYMENT {
            get {
                return ResourceManager.GetString("ADVANCE_PAYMENTS_RUSSIA_PREPAYMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete application category.
        /// </summary>
        public static string APPLICATION_CATEGORY_DELETE_RESULT_FAILED_DESCRIPTION {
            get {
                return ResourceManager.GetString("APPLICATION_CATEGORY_DELETE_RESULT_FAILED_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete application category.
        /// </summary>
        public static string APPLICATION_CATEGORY_DELETE_RESULT_FAILED_NAME {
            get {
                return ResourceManager.GetString("APPLICATION_CATEGORY_DELETE_RESULT_FAILED_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non empty application category cannot be deleted.
        /// </summary>
        public static string APPLICATION_CATEGORY_DELETE_RESULT_NON_EMPY_DESCRIPTION {
            get {
                return ResourceManager.GetString("APPLICATION_CATEGORY_DELETE_RESULT_NON_EMPY_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application category is not empty.
        /// </summary>
        public static string APPLICATION_CATEGORY_DELETE_RESULT_NON_EMPY_NAME {
            get {
                return ResourceManager.GetString("APPLICATION_CATEGORY_DELETE_RESULT_NON_EMPY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application category deletion was successful.
        /// </summary>
        public static string APPLICATION_CATEGORY_DELETE_RESULT_SUCCESS_DESCRIPTION {
            get {
                return ResourceManager.GetString("APPLICATION_CATEGORY_DELETE_RESULT_SUCCESS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application category delete success.
        /// </summary>
        public static string APPLICATION_CATEGORY_DELETE_RESULT_SUCCESS_NAME {
            get {
                return ResourceManager.GetString("APPLICATION_CATEGORY_DELETE_RESULT_SUCCESS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The host has reserved guest.
        /// </summary>
        public static string HOST_DELETE_RESULT_HOST_HAS_RESERVED_GUEST_DESCRIPTION {
            get {
                return ResourceManager.GetString("HOST_DELETE_RESULT_HOST_HAS_RESERVED_GUEST_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host has reserved guest.
        /// </summary>
        public static string HOST_DELETE_RESULT_HOST_HAS_RESERVED_GUEST_NAME {
            get {
                return ResourceManager.GetString("HOST_DELETE_RESULT_HOST_HAS_RESERVED_GUEST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The host is in use.
        /// </summary>
        public static string HOST_DELETE_RESULT_HOST_IN_USE_DESCRIPTION {
            get {
                return ResourceManager.GetString("HOST_DELETE_RESULT_HOST_IN_USE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host in use.
        /// </summary>
        public static string HOST_DELETE_RESULT_HOST_IN_USE_NAME {
            get {
                return ResourceManager.GetString("HOST_DELETE_RESULT_HOST_IN_USE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The host has reservation.
        /// </summary>
        public static string HOST_DELETE_RESULT_HOST_IS_RESERVED_DESCRIPTION {
            get {
                return ResourceManager.GetString("HOST_DELETE_RESULT_HOST_IS_RESERVED_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host is reserved.
        /// </summary>
        public static string HOST_DELETE_RESULT_HOST_IS_RESERVED_NAME {
            get {
                return ResourceManager.GetString("HOST_DELETE_RESULT_HOST_IS_RESERVED_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The host deletion was successful.
        /// </summary>
        public static string HOST_DELETE_RESULT_SUCCESS_DESCRIPTION {
            get {
                return ResourceManager.GetString("HOST_DELETE_RESULT_SUCCESS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host delete success.
        /// </summary>
        public static string HOST_DELETE_RESULT_SUCCESS_NAME {
            get {
                return ResourceManager.GetString("HOST_DELETE_RESULT_SUCCESS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified user account is disabled.
        /// </summary>
        public static string LOGIN_RESULT_ACCOUNT_DISABLED_DESCRIPTION {
            get {
                return ResourceManager.GetString("LOGIN_RESULT_ACCOUNT_DISABLED_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account disabled.
        /// </summary>
        public static string LOGIN_RESULT_ACCOUNT_DISABLED_NAME {
            get {
                return ResourceManager.GetString("LOGIN_RESULT_ACCOUNT_DISABLED_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is already logged in.
        /// </summary>
        public static string LOGIN_RESULT_ALREADY_LOGGED_IN_DESCRIPTION {
            get {
                return ResourceManager.GetString("LOGIN_RESULT_ALREADY_LOGGED_IN_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already logged in.
        /// </summary>
        public static string LOGIN_RESULT_ALREADY_LOGGED_IN_NAME {
            get {
                return ResourceManager.GetString("LOGIN_RESULT_ALREADY_LOGGED_IN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login was denied.
        /// </summary>
        public static string LOGIN_RESULT_DENIED_DESCRIPTION {
            get {
                return ResourceManager.GetString("LOGIN_RESULT_DENIED_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login denied.
        /// </summary>
        public static string LOGIN_RESULT_DENIED_NAME {
            get {
                return ResourceManager.GetString("LOGIN_RESULT_DENIED_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified login error.
        /// </summary>
        public static string LOGIN_RESULT_FAILED_DESCRIPTION {
            get {
                return ResourceManager.GetString("LOGIN_RESULT_FAILED_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        /// </summary>
        public static string LOGIN_RESULT_FAILED_NAME {
            get {
                return ResourceManager.GetString("LOGIN_RESULT_FAILED_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified user has insufficient balance.
        /// </summary>
        public static string LOGIN_RESULT_INSUFFICIENT_BALANCE_DESCRIPTION {
            get {
                return ResourceManager.GetString("LOGIN_RESULT_INSUFFICIENT_BALANCE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient balance.
        /// </summary>
        public static string LOGIN_RESULT_INSUFFICIENT_BALANCE_NAME {
            get {
                return ResourceManager.GetString("LOGIN_RESULT_INSUFFICIENT_BALANCE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified username or password is invalid.
        /// </summary>
        public static string LOGIN_RESULT_INVALID_CREDENTIALS_DESCRIPTION {
            get {
                return ResourceManager.GetString("LOGIN_RESULT_INVALID_CREDENTIALS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        public static string LOGIN_RESULT_INVALID_CREDENTIALS_NAME {
            get {
                return ResourceManager.GetString("LOGIN_RESULT_INVALID_CREDENTIALS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified host id is invalid.
        /// </summary>
        public static string LOGIN_RESULT_INVALID_HOST_ID_DESCRIPTION {
            get {
                return ResourceManager.GetString("LOGIN_RESULT_INVALID_HOST_ID_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid host.
        /// </summary>
        public static string LOGIN_RESULT_INVALID_HOST_ID_NAME {
            get {
                return ResourceManager.GetString("LOGIN_RESULT_INVALID_HOST_ID_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified parameters are invalid.
        /// </summary>
        public static string LOGIN_RESULT_INVALID_PARAMETERS_DESCRIPTION {
            get {
                return ResourceManager.GetString("LOGIN_RESULT_INVALID_PARAMETERS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameters.
        /// </summary>
        public static string LOGIN_RESULT_INVALID_PARAMETERS_NAME {
            get {
                return ResourceManager.GetString("LOGIN_RESULT_INVALID_PARAMETERS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified password is invalid.
        /// </summary>
        public static string LOGIN_RESULT_INVALID_PASSWORD_DESCRIPTION {
            get {
                return ResourceManager.GetString("LOGIN_RESULT_INVALID_PASSWORD_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password.
        /// </summary>
        public static string LOGIN_RESULT_INVALID_PASSWORD_NAME {
            get {
                return ResourceManager.GetString("LOGIN_RESULT_INVALID_PASSWORD_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified slot is invalid.
        /// </summary>
        public static string LOGIN_RESULT_INVALID_SLOT_DESCRIPTION {
            get {
                return ResourceManager.GetString("LOGIN_RESULT_INVALID_SLOT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid slot.
        /// </summary>
        public static string LOGIN_RESULT_INVALID_SLOT_NAME {
            get {
                return ResourceManager.GetString("LOGIN_RESULT_INVALID_SLOT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified user group id is invalid.
        /// </summary>
        public static string LOGIN_RESULT_INVALID_USER_GROUP_ID_DESCRIPTION {
            get {
                return ResourceManager.GetString("LOGIN_RESULT_INVALID_USER_GROUP_ID_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user group.
        /// </summary>
        public static string LOGIN_RESULT_INVALID_USER_GROUP_ID_NAME {
            get {
                return ResourceManager.GetString("LOGIN_RESULT_INVALID_USER_GROUP_ID_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified user id is invalid.
        /// </summary>
        public static string LOGIN_RESULT_INVALID_USER_ID_DESCRIPTION {
            get {
                return ResourceManager.GetString("LOGIN_RESULT_INVALID_USER_ID_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user.
        /// </summary>
        public static string LOGIN_RESULT_INVALID_USER_ID_NAME {
            get {
                return ResourceManager.GetString("LOGIN_RESULT_INVALID_USER_ID_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified username is invalid.
        /// </summary>
        public static string LOGIN_RESULT_INVALID_USERNAME_DESCRIPTION {
            get {
                return ResourceManager.GetString("LOGIN_RESULT_INVALID_USERNAME_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username.
        /// </summary>
        public static string LOGIN_RESULT_INVALID_USERNAME_NAME {
            get {
                return ResourceManager.GetString("LOGIN_RESULT_INVALID_USERNAME_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login in progress.
        /// </summary>
        public static string LOGIN_RESULT_LOGIN_IN_PROGRESS_DESCRIPTION {
            get {
                return ResourceManager.GetString("LOGIN_RESULT_LOGIN_IN_PROGRESS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress.
        /// </summary>
        public static string LOGIN_RESULT_LOGIN_IN_PROGRESS_NAME {
            get {
                return ResourceManager.GetString("LOGIN_RESULT_LOGIN_IN_PROGRESS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout in progress.
        /// </summary>
        public static string LOGIN_RESULT_LOGOUT_IN_PROGRESS_DESCRIPTION {
            get {
                return ResourceManager.GetString("LOGIN_RESULT_LOGOUT_IN_PROGRESS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress.
        /// </summary>
        public static string LOGIN_RESULT_LOGOUT_IN_PROGRESS_NAME {
            get {
                return ResourceManager.GetString("LOGIN_RESULT_LOGOUT_IN_PROGRESS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed due to maximum sessions reached.
        /// </summary>
        public static string LOGIN_RESULT_MAXIMUM_SESSIONS_REACHED_DESCRIPTION {
            get {
                return ResourceManager.GetString("LOGIN_RESULT_MAXIMUM_SESSIONS_REACHED_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum sessions reached.
        /// </summary>
        public static string LOGIN_RESULT_MAXIMUM_SESSIONS_REACHED_NAME {
            get {
                return ResourceManager.GetString("LOGIN_RESULT_MAXIMUM_SESSIONS_REACHED_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified user is not in waiting line.
        /// </summary>
        public static string LOGIN_RESULT_NOT_IN_WAITING_LINE_DESCRIPTION {
            get {
                return ResourceManager.GetString("LOGIN_RESULT_NOT_IN_WAITING_LINE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not in waiting line.
        /// </summary>
        public static string LOGIN_RESULT_NOT_IN_WAITING_LINE_NAME {
            get {
                return ResourceManager.GetString("LOGIN_RESULT_NOT_IN_WAITING_LINE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usergroup not allowed to login from manager.
        /// </summary>
        public static string LOGIN_RESULT_OPERATOR_USER_GROUP_DENIED_DESCRIPTION {
            get {
                return ResourceManager.GetString("LOGIN_RESULT_OPERATOR_USER_GROUP_DENIED_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usergroup login denied for operator.
        /// </summary>
        public static string LOGIN_RESULT_OPERATOR_USER_GROUP_DENIED_NAME {
            get {
                return ResourceManager.GetString("LOGIN_RESULT_OPERATOR_USER_GROUP_DENIED_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login is not allowed at this time due to age restrictions configuration.
        /// </summary>
        public static string LOGIN_RESULT_RESTRICTED_BY_AGE_DESCRIPTION {
            get {
                return ResourceManager.GetString("LOGIN_RESULT_RESTRICTED_BY_AGE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login age restrictions.
        /// </summary>
        public static string LOGIN_RESULT_RESTRICTED_BY_AGE_NAME {
            get {
                return ResourceManager.GetString("LOGIN_RESULT_RESTRICTED_BY_AGE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified slot is already in use.
        /// </summary>
        public static string LOGIN_RESULT_SLOT_IN_USE_DESCRIPTION {
            get {
                return ResourceManager.GetString("LOGIN_RESULT_SLOT_IN_USE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot is already in use.
        /// </summary>
        public static string LOGIN_RESULT_SLOT_IN_USE_NAME {
            get {
                return ResourceManager.GetString("LOGIN_RESULT_SLOT_IN_USE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user login was successful.
        /// </summary>
        public static string LOGIN_RESULT_SUCCESS_DESCRIPTION {
            get {
                return ResourceManager.GetString("LOGIN_RESULT_SUCCESS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login success.
        /// </summary>
        public static string LOGIN_RESULT_SUCCESS_NAME {
            get {
                return ResourceManager.GetString("LOGIN_RESULT_SUCCESS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russia.
        /// </summary>
        public static string TAX_SYSTEM_COUNTRY_RUSSIA {
            get {
                return ResourceManager.GetString("TAX_SYSTEM_COUNTRY_RUSSIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified.
        /// </summary>
        public static string TAX_SYSTEM_COUNTRY_UNSPECIFIED {
            get {
                return ResourceManager.GetString("TAX_SYSTEM_COUNTRY_UNSPECIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string TAX_SYSTEMS_RUSSIA_MAIN {
            get {
                return ResourceManager.GetString("TAX_SYSTEMS_RUSSIA_MAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patent system.
        /// </summary>
        public static string TAX_SYSTEMS_RUSSIA_PATENT_SYSTEM {
            get {
                return ResourceManager.GetString("TAX_SYSTEMS_RUSSIA_PATENT_SYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplified system minus expenses.
        /// </summary>
        public static string TAX_SYSTEMS_RUSSIA_SIMPLIFIED_SYSTEM_INCOME_MINUS_EXPSENSES {
            get {
                return ResourceManager.GetString("TAX_SYSTEMS_RUSSIA_SIMPLIFIED_SYSTEM_INCOME_MINUS_EXPSENSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplified system minus taxation.
        /// </summary>
        public static string TAX_SYSTEMS_RUSSIA_SIMPLIFIED_SYSTEM_INCOME_MINUS_TAXATION {
            get {
                return ResourceManager.GetString("TAX_SYSTEMS_RUSSIA_SIMPLIFIED_SYSTEM_INCOME_MINUS_TAXATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single agricultural tax.
        /// </summary>
        public static string TAX_SYSTEMS_RUSSIA_SINGLE_AGRICULTURAL_TAX {
            get {
                return ResourceManager.GetString("TAX_SYSTEMS_RUSSIA_SINGLE_AGRICULTURAL_TAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified.
        /// </summary>
        public static string TAX_SYSTEMS_UNSPECIFIED {
            get {
                return ResourceManager.GetString("TAX_SYSTEMS_UNSPECIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string VAT_RATES_RUSSIA_NONE {
            get {
                return ResourceManager.GetString("VAT_RATES_RUSSIA_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT0.
        /// </summary>
        public static string VAT_RATES_RUSSIA_VAT0 {
            get {
                return ResourceManager.GetString("VAT_RATES_RUSSIA_VAT0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT10.
        /// </summary>
        public static string VAT_RATES_RUSSIA_VAT10 {
            get {
                return ResourceManager.GetString("VAT_RATES_RUSSIA_VAT10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT20.
        /// </summary>
        public static string VAT_RATES_RUSSIA_VAT20 {
            get {
                return ResourceManager.GetString("VAT_RATES_RUSSIA_VAT20", resourceCulture);
            }
        }
    }
}
