using Gizmo.Shared.Resources.Autogenerated;
using System.ComponentModel.DataAnnotations;

namespace Gizmo
{
    /// <summary>
    /// Application category delete result.
    /// </summary>
    public enum ApplicationCategoryDeleteResult
    {
        /// <summary>
        /// Delete was successful.
        /// </summary>
        [Name("Application category delete success", nameof(Resources.APPLICATION_CATEGORY_DELETE_RESULT_SUCCESS_NAME))]
        [ExtendedDescription("The application category deletion was successful", nameof(Resources.APPLICATION_CATEGORY_DELETE_RESULT_SUCCESS_DESCRIPTION))]
        Success = 0,

        /// <summary>
        /// Failed to delete application category.
        /// </summary>
        [Name("Failed to delete application category", nameof(Resources.APPLICATION_CATEGORY_DELETE_RESULT_FAILED_NAME))]
        [ExtendedDescription("Failed to delete application category", nameof(Resources.APPLICATION_CATEGORY_DELETE_RESULT_FAILED_DESCRIPTION))]
        Failed = 1,
        /// <summary>
        /// Failed to delete application category.
        /// </summary>
        [Name("Failed to delete application category", nameof(Resources.APPLICATION_CATEGORY_DELETE_RESULT_NON_EMPY_NAME))]
        [ExtendedDescription("Failed to delete application category", nameof(Resources.APPLICATION_CATEGORY_DELETE_RESULT_NON_EMPY_DESCRIPTION))]
        NonEmpty = 2,

    }
}
