using Gizmo.Shared.Resources.Autogenerated;
using System.ComponentModel.DataAnnotations;

namespace Gizmo
{
    /// <summary>
    /// Host delete result.
    /// </summary>
    public enum HostDeleteResult
    {
        /// <summary>
        /// Delete was successful.
        /// </summary>
        [Name("Host delete success", nameof(Resources.HOST_DELETE_RESULT_SUCCESS_NAME))]
        [ExtendedDescription("The host deletion was successful", nameof(Resources.HOST_DELETE_RESULT_SUCCESS_DESCRIPTION))]
        Success = 0,

        /// <summary>
        /// Delete was successful.
        /// </summary>
        [Name("Host in use", nameof(Resources.HOST_DELETE_RESULT_HOST_IN_USE_NAME))]
        [ExtendedDescription("The host is in use", nameof(Resources.HOST_DELETE_RESULT_HOST_IN_USE_DESCRIPTION))]
        HostInUse = 1,

        /// <summary>
        /// Delete was successful.
        /// </summary>
        [Name("Host has reserved guest", nameof(Resources.HOST_DELETE_RESULT_HOST_HAS_RESERVED_GUEST_NAME))]
        [ExtendedDescription("The host has reserved guest", nameof(Resources.HOST_DELETE_RESULT_HOST_HAS_RESERVED_GUEST_DESCRIPTION))]
        HostHasReservedGuest = 2,

        /// <summary>
        /// Delete was successful.
        /// </summary>
        [Name("Host is reserved", nameof(Resources.HOST_DELETE_RESULT_HOST_IS_RESERVED_NAME))]
        [ExtendedDescription("The host has reservation", nameof(Resources.HOST_DELETE_RESULT_HOST_IS_RESERVED_DESCRIPTION))]
        HostIsReserved = 3
    }
}
