<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="9.0.0" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Gizmo.Web.Components\Gizmo.Web.Components.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="src\" />
    <Folder Include="wwwroot\js\" />
  </ItemGroup>

  <Target Name="NpmInstall" BeforeTargets="Build">
    <Exec Command="npm install" WorkingDirectory="$(ProjectDir)" />
  </Target>

  <Target Name="NpmBuild" AfterTargets="NpmInstall">
    <Exec Command="npm run build" WorkingDirectory="$(ProjectDir)" />
  </Target>

</Project>
